name: Toto
on:
 push:
  branches: 
   - "dev"
jobs: 
 Test:
  runs-on: ubuntu-latest
  steps:
   - name: Test 1
     run: echo "juji"

     
#  Create-issue:
#   needs: [Test]
#   runs-on: ubuntu-latest
#   if: always() && (needs.Test.result == 'failure')
#   steps: 
#    - name: create issue
#      uses: actions-ecosystem/action-create-issue@v1
#      with:
#       github_token: ${{ secrets.GITHUB_TOKEN }} 
#       title: Problème lors du test
#       body: |
#        ## A faire
#        Tout a pété
#    - name: afficher secrets
#      run: echo ${{ secrets.MANAGE_TOKEN }}





#      uses: actions/checkout@v3
#    - name: test 1
#      run: echo 1
#    - name: test 2
#      run: echo "test 2"
#  Build:
#   needs: [Test]
#   runs-on: ubuntu-latest
#   steps: 
#    - name: Build
#      run: echo 1
#  Check:
#    needs: [Test, Build]
#    runs-on: ubuntu-latest
#    #if: ${{ always() }}
#    if: always() && (needs.Test.result == 'failure' || needs.Build.result == 'failure')
#    steps:
#     - name: "Mail"
#       run: echo "mail"



  #  - name: Envoi mail
  #    if: ${{ failure() }}
  #    run: echo "Envoi mail si le test echoue"
#  Build:
#   needs: [MonPremierJob] 
#   runs-on: ubuntu-latest
#   steps:
#    - name: build de l'app
#      run: echo "Je build"



