name: Toto
on: [push]
jobs: 
 MonPremierJob:
  runs-on: ubuntu-latest
  steps:
   - name: Recup du repo
     uses: actions/checkout@v3
   - name: test 1
     run: exit 1
   - name: test 2
     if: {{ always() }}
     run: echo "test 2"
   - name: Envoi mail
     if: ${{ failure() }}
     run: echo "Envoi mail si le test echoue"
#  Build:
#   needs: [MonPremierJob] 
#   runs-on: ubuntu-latest
#   steps:
#    - name: build de l'app
#      run: echo "Je build"



